### ISSUE TITLE
can't login to mysql using default login

### ISSUE THREAD

**Issue by Nico0o00o** [betoca/docker.cloudera-spark#1]
mysql comes installed on the container, however the default username "root@localhost" with no password doesn't let you in. Is there a pre-configured password for root? if so, what is it? 

Am I completely missing something?

Thanks @betoca

**Comment by betoca** [comment]
This would be default quickstart cloudera user/password
you should be able to log in with root/cloudera
`mysql -uroot -pcloudera`
